name: CI Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch on Push and any branches on PR
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
env:
  CI: true
  PREFERRED_WORKSPACE_MANAGER: npm

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [14, 16]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - if: matrix.node == '14'
        run: npm install --global npm@8

      - run: node --version
      - run: npm --version

      - name: Install NPM dependencies
        run: npm ci

      - name: Run all workspace TSC builds
        run: npm run build

      - name: Run Jest unit tests
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run jest:ci

      - name: Upload Jest coverage to Codecov
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: bash <(curl -s https://codecov.io/bash)
